### ISSUE TITLE
Use correct Derivation Paths

### ISSUE THREAD

**Issue by HashEngineering** [coreyphillips/moonshine#13]
### Part 1
There are 2 places where the derivation path is specified in the format  `m/${keyDerivationPath}'/0'/0'/${networkValue}/0`, but it should be in the format `m/${keyDerivationPath}'/${networkValue}'/0'`

**Incorrect:**
https://github.com/coreyphillips/moonshine/blob/672d801653feb812dcce8aa1d6a292daa4fe9fb5/src/components/Settings.js#L998
https://github.com/coreyphillips/moonshine/blob/c8716893198ebfedab05e729cc0da320a8054f49/src/utils/helpers.js#L836

basically, this is not needed: `0'/0'/`

**Correct:**
https://github.com/coreyphillips/moonshine/blob/c8716893198ebfedab05e729cc0da320a8054f49/src/utils/helpers.js#L563

### Part 2 - address derivation for different coins:
https://github.com/coreyphillips/moonshine/blob/c8716893198ebfedab05e729cc0da320a8054f49/src/utils/helpers.js#L537
https://github.com/coreyphillips/moonshine/blob/c8716893198ebfedab05e729cc0da320a8054f49/src/utils/helpers.js#L835

These two spots will derive the correct addresses in subsequent code for Bitcoin (0) and TestNet (1) for any coin.  However the 0 should be 2 for litecoin.  Other software that supports multiple coins has used modules like coininfo where the coin_type is included in coin's network information. (e.g. https://github.com/cryptocoinjs/coininfo/blob/master/lib/coins/ltc.js#L27).  Since the coin_type is 0 for litecoin, the addresses generated by the app do not match those generated by https://iancoleman.io/bip39/

one solution is to include that value in the `networks` data:  https://github.com/coreyphillips/moonshine/blob/c8716893198ebfedab05e729cc0da320a8054f49/src/utils/networks.js#L2

**Comment by coreyphillips** [comment]
To address this, I'm thinking the following:
 - Implement a script that will attempt to detect funds on the current (incorrect) derivation paths when the app is loaded.
 - If funds are detected it will alert the user, but continue to use the old derivation paths so that they can continue to use the wallet normally.
 - If no funds are detected, it will use the new, correct derivation paths. No alert necessary.

This should only affect Litecoin & Litecoin Testnet users. The script will be removed from the published version of the app. If users import their mnemonic phrase from the old beta build into the newly published app they'll be able to access their LTC or TLTC by adding the old derivation path using #15.

**Comment by gruve-p** [comment]
This affects Bitcoin Testnet users also.

**Comment by coreyphillips** [comment]
This should be resolved as of 413c2459ed8c4813492228b83087dd993a04cb60. Leaving this open to continue testing.

**Comment by HashEngineering** [comment]
Excellent work.  I look forward to working with this further.
