### ISSUE TITLE
Notification on main screen when amount of crypto incoming

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#45]
Would be nice to have notification if amount of crypto came. 
I tested with Android

**Comment by coreyphillips** [comment]
I do not intend on adding local notifications at this time as it would require requesting additional permissions and since I do not intend on adding remote push notifications it may create confusion for users who would be expecting remote notifications while the app is in the background. I will, however will mark this issue as an "enhancement" for future reference.

Current behavior at the time of this writing - The app will vibrate to notify the user of an incoming transaction when the the app is open. The app will not notify the user if the app is closed. Only upon opening the app will they be notified.
