### ISSUE TITLE
unable to generate new receiving  address

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#48]
I did extensive test on receiving small amount to Legacy wallet from my mates Bech32 wallet.
Both Moonshine based.
after 5 random addresses 1 address start repeating.
it was same until it received some amount of crypto. 
Can I always get new random address without confirmation of receiving crypto on previous generated address?

**Comment by coreyphillips** [comment]
Hey cryply, in Moonshine's current form (v0.3.5) user's are currently not able to generate addresses at will. A new address is only generated when it has detected/received a transaction. Once it detects a tx it will generate a new receiving address. This is primarily due to the lack of an adjustable gap limit option in Moonshine and to prevent confusion for users that may have created 50+ empty addresses, sent funds to the 50th address, re-imported their wallet, forgot to set their gap limit to 50 and become concerned when they don't see their balance.

While [this](https://github.com/coreyphillips/moonshine/issues/23) is currently a blocker I would be happy to make this a feature request.

**Comment by cryply** [comment]
Hey Corey
For lame users ur wallet has many advanced features. :)
But I consider 50 addresses a joke. how can I extend that gap limit?
can it be unlimited? Where can I see how many already were generated?

**Comment by coreyphillips** [comment]
Lol, it's just something that is very easy to mess up or overlook even for advanced users. If I do eventually add this as a feature I think it will only become enabled once the user increases their gap limit in the settings and even then the app will only allow the user to create as many addresses as their set gap limit allows. It would make creating multiple 0-balance addresses very intentional and help prevent accidental misuse. Adding a list of all addresses generated by the app would definitely be helpful as well. I added that as a feature request [here](https://github.com/coreyphillips/moonshine/issues/51).
