### ISSUE TITLE
generated address never received crypto

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#49]
I did testing of sending crypto to 1 bech32 1 segwit and 1 legacy address.
I did generate them one by one and gave to my friend.
he send money to all of them. 
Funny but Legacy wallet was not showing anything.
I check blockexplorer and found transaction but never in wallet.

How can I debug Issue? Can I enumerate all addresses? Do u have JS version of wallet where I can import wallet and find out why TX not appears?

**Comment by coreyphillips** [comment]
Hey cryply, sorry to see you're having issues. So, Moonshine doesn't consolidate transactions between Legacy, Segwit & Native-Segwit (Bech32). Meaning, whenever you swap between each address type in the Settings it clears previous tx's and restarts a search for tx's on that specific derivation path beginning back at 0. So if you have your wallet set to the Bech32 address type and you receive BTC on your Legacy address, Moonshine is not going to report it to you. You will however be able to see and spend that transaction once you toggle to the Legacy address type in Settings. What you can also do is create three separate wallets with the same mnemonic within the app and set one to Legacy, another to Segwit and the last to Bech32 so that you can easily switch between them as needed. If for any reason you need to rescan your wallet starting back at index 0 you can tap the "Rescan Wallet" option in Settings towards the bottom.

Regarding a tool for offline debugging, I highly recommend https://iancoleman.io/bip39/

**Comment by cryply** [comment]
Hey Corey
Thanks for prompt response.
My tester was using moonshine. And switch it to bech32 mode.
In that mode he sent crypto  to my legacy address.
This is acceptable right? It is normally working for me. I would say. It was always working.
I was trying to reproduce without success. But TX in blockchain. So I can investigate now whats went wrong. Thanks a lot for link

**Comment by coreyphillips** [comment]
Sending from Bech32->Legacy or any other combination of address types is definitely acceptable. The primary reasons that this may happen are listed above. When re-running the tests just ensure the mnemonic phrase matches the original wallet you sent to and that you swap to "Legacy" in the Settings. The offline tool should help narrow it down as well.
